DEFAULT_SMTP_SERVER = ''
DEFAULT_SMTP_PORT = 25
DEFAULT_SMTP_USER = ''
DEFAULT_SMTP_PASSWORD = ''

SENDER_EMAIL_ADDR = 'no-replay@spaceone.dev'

NOTIFICATION_TYPE_DEFAULT_COLOR = '#858895'

NOTIFICATION_TYPE_COLOR_MAP = {
    'INFO': '#A7A9B2',
    'ERROR': '#FF6A6A',
    'SUCCESS': '#60B731',
    'WARNING': '#FFCE02',
    'DEFAULT': '#858895'
}